title: String Morpher
theme: just-the-docs
url: "https://ssolweb.github.io"
baseurl: "/string-morpher" # the subpath of your site, e.g. /blog
repository: ssolweb/string-morpher/
email: vinicius.vts@gmail.com
description: A powerful string manipulation library for PHP.
permalink: pretty
# color_scheme: dark
# logo: /assets/logo.jpg
favicon_ico: /assets/favicon.ico
#footer
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."

color_scheme: ssw_custom.scss

defaults:
  - scope:
      path:
      type: "pages"
    values:
      layout: "default"

nav_external_links:
  - title: Changelog on GitHub
    url: https://github.com/SSolWEB/string-morpher/releases
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false
