name: Main CI Validations

on:
  push:
    branches:
      - main

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: Test changed-files
    outputs:
      src: ${{ steps.changed-files-yaml.outputs.src_any_changed }}
      tests: ${{ steps.changed-files-yaml.outputs.tests_any_changed }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Get changed files
        id: changed-files-yaml
        uses: tj-actions/changed-files@70069877f29101175ed2b055d210fe8b1d54d7d7 # v45.0.6
        with:
          files_yaml: |
            src:
              - src/**
            tests:
              - tests/**

  call-php-tests:
    needs: changed_files
    if: |
      ${{ needs.changed_files.outputs.src == 'true' || needs.changed_files.outputs.tests == 'true' }}
    uses: ./.github/workflows/php-tests.yml

  call-php-linter:
    needs: changed_files
    if: |
      ${{ needs.changed_files.outputs.src == 'true' || needs.changed_files.outputs.tests == 'true' }}
    uses: ./.github/workflows/php-linter.yml
