name: Pull Request Validation

on:
  pull_request:
    branches:
      - main

jobs:
  add-reviewer:
    name: Add Reviewer
    runs-on: ubuntu-latest
    steps:
    - name: Add Reviewers
      uses: madrapps/add-reviewers@v1
      with:
        token: ${{ secrets.PAT_GH_PAGE }}
        reviewers: viniciusvts
        re-request-when-approved: true
        re-request-when-changes-requested: true

  changed_files:
    runs-on: ubuntu-latest
    name: Test changed-files
    outputs:
      docs: ${{ steps.changed-files-yaml.outputs.docs_any_changed }}
      src: ${{ steps.changed-files-yaml.outputs.src_any_changed }}
      tests: ${{ steps.changed-files-yaml.outputs.tests_any_changed }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Get changed files
        id: changed-files-yaml
        uses: tj-actions/changed-files@70069877f29101175ed2b055d210fe8b1d54d7d7 # v45.0.6
        with:
          files_yaml: |
            docs:
              - docs/**
            src:
              - src/**
            tests:
              - tests/**

  run-tests:
    name: Run PHPUnit
    runs-on: ubuntu-latest
    needs: changed_files
    if: |
      ${{ needs.changed_files.outputs.src == 'true' || needs.changed_files.outputs.tests == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist

      - name: Run PHPUnit
        run: vendor/bin/phpunit

  run-linter:
    name: Run PHP_CodeSniffer
    runs-on: ubuntu-latest
    needs: changed_files
    if: |
      ${{ needs.changed_files.outputs.src == 'true' || needs.changed_files.outputs.tests == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist

      - name: Run PHP_CodeSniffer
        run: vendor/bin/phpcs

  run-documentation-check:
    name: Documentation check
    runs-on: ubuntu-latest
    needs: changed_files
    if: ${{ needs.changed_files.outputs.docs == 'true' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62 # v47
        with:
          files: |
            docs/**

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install dependencies
        run: |
          cd docs
          gem install bundler
          bundle install

      - name: Build the site
        run: |
          cd docs
          bundle exec jekyll build --destination ./build
